### ISSUE TITLE
Failed at the microtime@1.0.1 install script

### ISSUE THREAD

**Issue by techhysahil** [wadey/node-microtime#24]
Detail of the issue:

npm ERR! microtime@1.0.1 install: `node-gyp rebuild`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the microtime@1.0.1 install script.
npm ERR! This is most likely a problem with the microtime package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls microtime
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodej
s\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd c:\mpp\kitsune
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! syscall spawn
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! not ok code 0

i am using windows 7 64 bit.
Node v-0.10.33

please help me!

**Comment by alsotang** [comment]
can't not install this package at 0.10.36 too

**Comment by wadey** [comment]
Closing as I have received no other information. It looks like your build environments are incomplete.

**Comment by takhello** [comment]
213 verbose node v12.13.1
214 verbose npm  v6.12.1
215 error code ELIFECYCLE
216 error errno 7
217 error microtime@1.0.1 install: `node-gyp rebuild`
217 error Exit status 7
218 error Failed at the microtime@1.0.1 install script.
218 error This is probably not a problem with npm. There is likely additional logging output above.
219 verbose exit [ 7, true ]

**Comment by wadey** [comment]
@takhello please upgrade to v3.0.0
