### ISSUE TITLE
Fails to install on Travis using Io.js

### ISSUE THREAD

**Issue by SimenB** [wadey/node-microtime#26]
Example log: https://travis-ci.org/webpack/webpack/jobs/60000430

Any idea? It installs fine on my Mac using Io.js installed with `nvm` and the same `npm`.

I'm installing Ubuntu right now to test with Linux.

EDIT: Clean ubuntu 15.04 install builds fine...

**Comment by wadey** [comment]
The error in your linked build says:

    gyp ERR! stack Error: 404 status code downloading tarball

Which makes me think it was a temporary issue with npm in downloading the package or the node headers to build from sources. Can you attempt again?

**Comment by SimenB** [comment]
The weird thing is we needed to update npm to >2 on 0.10, but that caused the iojs build I linked to fail. Upgrading npm on only 0.10 and not 0.12 or iojs made the build pass again. 

It's not my repo, so I'm not gonna mess with it.  Works fine now :smile:
