### ISSUE TITLE
Electron: Module version mismatch. Expected 43, got 14

### ISSUE THREAD

**Issue by Sendoushi** [wadey/node-microtime#30]
Hey guys,
Using Electron to build an app and getting an error importing with `require('microtime');`

The error I get is:
`Module version mismatch. Expected 43, got 14`

Ideas on how to solve?

**Comment by wadey** [comment]
Can you provide some more information? What is the electron or npm command you are running to attempt the install? What version of microtime are you trying to use? Can you paste the full error log.

If you can give me full steps to reproduce, I can work on fixing it. Otherwise, it is very hard to do.

**Comment by Sendoushi** [comment]
I'm on a Mac by the way.

So, I created a repo for this (after you clone please tell me so I can remove it).
https://github.com/Sendoushi/testmicrotimeelectron

You clone and then: npm install && npm run build && npm run start

You'll see the error in the console.

**Comment by Sendoushi** [comment]
Just found that electron is built on top of io would that be the problem?

**Comment by wadey** [comment]
The latest version of node-microtime works with iojs (both 1.x and 2.x). The trick is that you need to make sure the `npm` version you are using is using the same version of iojs as electron (which appears to be iojs v1.6.3 in the version your example uses).

If I use npm/iojs 1.6.3 to build your example, it works:

```
$ node --version
v1.6.3
$ npm install
…
$ npm run build
…
$ npm run start

> testmicrotime@0.0.0 start /…/testmicrotimeelectron
> electron .

[37403:0527/175259:INFO:renderer_main.cc(200)] Renderer process started
[37401:0527/175300:INFO:CONSOLE(3)] "1432763580045810", source: file:///…/testmicrotimeelectron/app.js (3)
```
