### ISSUE TITLE
Install issues on Windows 8.1

### ISSUE THREAD

**Issue by awayken** [wadey/node-microtime#31]
I'm running into issues trying to install this on Windows 8.1 with iojs v2.0.2 and npm v2.9.0. I'm not sure if it's me or Windows or iojs or what.

Here is what I get for an error:
```
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\Program Files\iojs\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1009:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "D:\\Program Files\\iojs\\node.exe" "D:\\Program Files\\iojs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Sites\cssnext\node_modules\microtime
gyp ERR! node -v v2.0.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "D:\\Program Files\\iojs\\node.exe" "D:\\Program Files\\iojs\\node_modules\\npm\\bin\\npm-cli.js" "install" "microtime"
npm ERR! node v2.0.2
npm ERR! npm  v2.9.0
npm ERR! code ELIFECYCLE

npm ERR! microtime@1.4.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the microtime@1.4.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the microtime package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls microtime
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Sites\cssnext\npm-debug.log
```

Do you want me to attach the npm-debug.log file?

**Comment by wadey** [comment]
Sure you can attach the debug file and we can see if there is anything helpful in it. Last windows build I have done was with iojs 2.0.1 and it built fine:

- https://ci.appveyor.com/project/WadeSimmons/node-microtime/build/17/job/0hoyab2ls50vy5rg

I'm running a new build with 2.0.2 to double check that it still builds on Windows.

**Comment by wadey** [comment]
ah the latest build built with iojs 2.1.0, but it worked:

- https://ci.appveyor.com/project/WadeSimmons/node-microtime/build/job/7cmifwiajbwr0rnd

**Comment by awayken** [comment]
Well, that's bizarre. Today it installed just fine.

The only thing that changed for me is that I installed a newer version of Visual Studio (unrelated to this issue), so perhaps that upgraded some dependent driver or something. Who knows.

Thanks for your help!
