### ISSUE TITLE
Unable to use with iojs-v3.0.0

### ISSUE THREAD

**Issue by peteyy** [wadey/node-microtime#33]
When trying to use with the latest iojs I get the following error.

/Users/peteyy/Projects/trace-nodejs/node_modules/microtime/node_modules/bindings/bindings.js:83
        throw e
        ^

Error: Module version mismatch. Expected 45, got 44.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (/Users/peteyy/Projects/trace-nodejs/node_modules/microtime/node_modules/bindings/bindings.js:76:44)

**Comment by wadey** [comment]
Thanks for the report. It looks like we need to update to `nan 2.0.x`, but some changes need to be made to make it compile. I'll try to look at it later today or Monday.

**Comment by wadey** [comment]
I have released `microtime 2.0.0` which supports `iojs 3.0.0`. Compatibility back to nodejs 0.8 has been preserved.

Build results:
Linux: https://travis-ci.org/wadey/node-microtime/builds/74858909
Windows: https://ci.appveyor.com/project/WadeSimmons/node-microtime/build/28

**Comment by psorowka** [comment]
Thanks for that!

And especially commit c25d93c just saved my life. Is there any source/doc explaining what's going on there at travis, needing this pampering?

**Comment by wadey** [comment]
I found that Travis fix in the `nan` repo, not sure why it's needed but it works for now. I'm guessing it's a temporary thing.
