### ISSUE TITLE
What's the breaking change from 1.x to 2.x?

### ISSUE THREAD

**Issue by jedmao** [wadey/node-microtime#35]
I can't find a changelog.

**Comment by wadey** [comment]
I released as 2.x because the dependency `nan` went from 1.x to 2.x. But shortly after I did the release I realized that was foolish because nothing from the nan dependency leaks through in the api. So I released 1.5.0 with the same fixes as 2.0.0.

https://github.com/wadey/node-microtime/tree/1.x
