### ISSUE TITLE
Fails to build on Gentoo

### ISSUE THREAD

**Issue by jlpoolen** [wadey/node-microtime#41]
themis pasteboard # npm install microtime
    -
    > microtime@0.3.3 install /usr/local/src/pasteboard/node_modules/microtime
    > node-gyp rebuild

    make: Entering directory '/usr/local/src/pasteboard/node_modules/microtime/build'
      CXX(target) Release/obj.target/microtime/src/microtime.o
    ../src/microtime.cc:10:32: error: âArgumentsâ does not name a type
     static Handle<Value> Now(const Arguments &args) {
                                    ^
    In file included from ../src/microtime.cc:1:0:
    /root/.node-gyp/0.12.6/deps/v8/include/v8.h: In function âv8::Handle<v8::Value> Now(const int&)â:
    /root/.node-gyp/0.12.6/deps/v8/include/v8.h:816:13: error: âv8::HandleScope::HandleScope()â is protected
       V8_INLINE HandleScope() {}
                 ^
    ../src/microtime.cc:11:17: error: within this context
         HandleScope scope;
                     ^
    ../src/microtime.cc:17:68: error: âThrowExceptionâ was not declared in this scope
             return ThrowException(ErrnoException(errno, "gettimeofday"));
                                                                        ^
    ../src/microtime.cc:20:18: error: âclass v8::HandleScopeâ has no member named âCloseâ
         return scope.Close(Number::New((t.tv_sec * 1000000.0) + t.tv_usec));
                      ^
    ../src/microtime.cc:20:70: error: no matching function for call to âv8::Number::New(double)â
         return scope.Close(Number::New((t.tv_sec * 1000000.0) + t.tv_usec));
                                                                          ^
    ../src/microtime.cc:20:70: note: candidate is:
    In file included from ../src/microtime.cc:1:0:
    /root/.node-gyp/0.12.6/deps/v8/include/v8.h:1999:24: note: static v8::Local<v8::Number> v8::Number::New(v8::Isolate*, double)
       static Local<Number> New(Isolate* isolate, double value);
                            ^
    /root/.node-gyp/0.12.6/deps/v8/include/v8.h:1999:24: note:   candidate expects 2 arguments, 1 provided
    ../src/microtime.cc: At global scope:
    ../src/microtime.cc:23:38: error: âArgumentsâ does not name a type
     static Handle<Value> NowDouble(const Arguments &args) {
                                          ^
    In file included from ../src/microtime.cc:1:0:
    /root/.node-gyp/0.12.6/deps/v8/include/v8.h: In function âv8::Handle<v8::Value> NowDouble(const int&)â:
    /root/.node-gyp/0.12.6/deps/v8/include/v8.h:816:13: error: âv8::HandleScope::HandleScope()â is protected
       V8_INLINE HandleScope() {}
                 ^
    ../src/microtime.cc:24:17: error: within this context
         HandleScope scope;
                     ^
    ../src/microtime.cc:30:68: error: âThrowExceptionâ was not declared in this scope
             return ThrowException(ErrnoException(errno, "gettimeofday"));
                                                                        ^
    ../src/microtime.cc:33:18: error: âclass v8::HandleScopeâ has no member named âCloseâ
         return scope.Close(Number::New(t.tv_sec + (t.tv_usec * 0.000001)));
                      ^
    ../src/microtime.cc:33:69: error: no matching function for call to âv8::Number::New(double)â
         return scope.Close(Number::New(t.tv_sec + (t.tv_usec * 0.000001)));
                                                                         ^
    ../src/microtime.cc:33:69: note: candidate is:
    In file included from ../src/microtime.cc:1:0:
    /root/.node-gyp/0.12.6/deps/v8/include/v8.h:1999:24: note: static v8::Local<v8::Number> v8::Number::New(v8::Isolate*, double)
       static Local<Number> New(Isolate* isolate, double value);
                            ^
    /root/.node-gyp/0.12.6/deps/v8/include/v8.h:1999:24: note:   candidate expects 2 arguments, 1 provided
    ../src/microtime.cc: At global scope:
    ../src/microtime.cc:36:38: error: âArgumentsâ does not name a type
     static Handle<Value> NowStruct(const Arguments &args) {
                                          ^
    In file included from ../src/microtime.cc:1:0:
    /root/.node-gyp/0.12.6/deps/v8/include/v8.h: In function âv8::Handle<v8::Value> NowStruct(const int&)â:
    /root/.node-gyp/0.12.6/deps/v8/include/v8.h:816:13: error: âv8::HandleScope::HandleScope()â is protected
       V8_INLINE HandleScope() {}
                 ^
    ../src/microtime.cc:37:17: error: within this context
         HandleScope scope;
                     ^
    ../src/microtime.cc:43:68: error: âThrowExceptionâ was not declared in this scope
             return ThrowException(ErrnoException(errno, "gettimeofday"));
                                                                        ^
    ../src/microtime.cc:46:38: error: invalid conversion from âintâ to âv8::Isolate â [-fpermissive]
         Local<Array> array = Array::New(2);
                                          ^
    In file included from ../src/microtime.cc:1:0:
    /root/.node-gyp/0.12.6/deps/v8/include/v8.h:2417:23: note: initializing argument 1 of âstatic v8::Local<v8::Array> v8::Array::New(v8::Isolate*, int)â
       static Local<Array> New(Isolate* isolate, int length = 0);
                           ^
    ../src/microtime.cc:47:30: error: no matching function for call to âv8::Integer::New(int)â
         array->Set(Integer::New(0), Uint32::New(t.tv_sec));
                                  ^
    ../src/microtime.cc:47:30: note: candidate is:
    In file included from ../src/microtime.cc:1:0:
    /root/.node-gyp/0.12.6/deps/v8/include/v8.h:2012:25: note: static v8::Local<v8::Integer> v8::Integer::New(v8::Isolate*, int32_t)
       static Local<Integer> New(Isolate* isolate, int32_t value);
                             ^
    /root/.node-gyp/0.12.6/deps/v8/include/v8.h:2012:25: note:   candidate expects 2 arguments, 1 provided
    ../src/microtime.cc:47:53: error: no matching function for call to âv8::Uint32::New(__time_t&)â
         array->Set(Integer::New(0), Uint32::New(t.tv_sec));
                                                         ^
    ../src/microtime.cc:47:53: note: candidate is:
    In file included from ../src/microtime.cc:1:0:
    /root/.node-gyp/0.12.6/deps/v8/include/v8.h:2012:25: note: static v8::Local<v8::Integer> v8::Integer::New(v8::Isolate*, int32_t)
       static Local<Integer> New(Isolate* isolate, int32_t value);
                             ^
    /root/.node-gyp/0.12.6/deps/v8/include/v8.h:2012:25: note:   candidate expects 2 arguments, 1 provided
    ../src/microtime.cc:48:30: error: no matching function for call to âv8::Integer::New(int)â
         array->Set(Integer::New(1), Uint32::New(t.tv_usec));
                                  ^
    ../src/microtime.cc:48:30: note: candidate is:
    In file included from ../src/microtime.cc:1:0:
    /root/.node-gyp/0.12.6/deps/v8/include/v8.h:2012:25: note: static v8::Local<v8::Integer> v8::Integer::New(v8::Isolate*, int32_t)
       static Local<Integer> New(Isolate* isolate, int32_t value);
                             ^
    /root/.node-gyp/0.12.6/deps/v8/include/v8.h:2012:25: note:   candidate expects 2 arguments, 1 provided
    ../src/microtime.cc:48:54: error: no matching function for call to âv8::Uint32::New(__suseconds_t&)â
         array->Set(Integer::New(1), Uint32::New(t.tv_usec));
                                                          ^
    ../src/microtime.cc:48:54: note: candidate is:
    In file included from ../src/microtime.cc:1:0:
    /root/.node-gyp/0.12.6/deps/v8/include/v8.h:2012:25: note: static v8::Local<v8::Integer> v8::Integer::New(v8::Isolate*, int32_t)
       static Local<Integer> New(Isolate* isolate, int32_t value);
                             ^
    /root/.node-gyp/0.12.6/deps/v8/include/v8.h:2012:25: note:   candidate expects 2 arguments, 1 provided
    ../src/microtime.cc:50:18: error: âclass v8::HandleScopeâ has no member named âCloseâ
         return scope.Close(array);
                      ^
    In file included from ../src/microtime.cc:1:0:
    /root/.node-gyp/0.12.6/deps/v8/include/v8.h: In function âvoid init(v8::Handle<v8::Object>)â:
    /root/.node-gyp/0.12.6/deps/v8/include/v8.h:816:13: error: âv8::HandleScope::HandleScope()â is protected
       V8_INLINE HandleScope() {}
                 ^
    ../src/microtime.cc:55:17: error: within this context
         HandleScope scope;
                     ^
    ../src/microtime.cc:57:39: error: no matching function for call to âNODE_SET_METHOD(v8::Handle<v8::Object>&, const char [4], v8::Handle<v8::Value> (&)(const int&))â
         NODE_SET_METHOD(target, "now", Now);
                                           ^
    ../src/microtime.cc:57:39: note: candidate is:
    In file included from ../src/microtime.cc:2:0:
    /root/.node-gyp/0.12.6/src/node.h:228:13: note: template<class TypeName> void node::NODE_SET_METHOD(const TypeName&, const char*, v8::FunctionCallback)
     inline void NODE_SET_METHOD(const TypeName& recv,
                 ^
    /root/.node-gyp/0.12.6/src/node.h:228:13: note:   template argument deduction/substitution failed:
    ../src/microtime.cc:57:39: note:   cannot convert âNowâ (type âv8::Handle<v8::Value>(const int&)â) to type âv8::FunctionCallback {aka void (*)(const v8::FunctionCallbackInfo<v8::Value>&)}â
         NODE_SET_METHOD(target, "now", Now);
                                           ^
    ../src/microtime.cc:58:51: error: no matching function for call to âNODE_SET_METHOD(v8::Handle<v8::Object>&, const char [10], v8::Handle<v8::Value> (&)(const int&))â
         NODE_SET_METHOD(target, "nowDouble", NowDouble);
                                                       ^
    ../src/microtime.cc:58:51: note: candidate is:
    In file included from ../src/microtime.cc:2:0:
    /root/.node-gyp/0.12.6/src/node.h:228:13: note: template<class TypeName> void node::NODE_SET_METHOD(const TypeName&, const char*, v8::FunctionCallback)
     inline void NODE_SET_METHOD(const TypeName& recv,
                 ^
    /root/.node-gyp/0.12.6/src/node.h:228:13: note:   template argument deduction/substitution failed:
    ../src/microtime.cc:58:51: note:   cannot convert âNowDoubleâ (type âv8::Handle<v8::Value>(const int&)â) to type âv8::FunctionCallback {aka void (*)(const v8::FunctionCallbackInfo<v8::Value>&)}â
         NODE_SET_METHOD(target, "nowDouble", NowDouble);
                                                       ^
    ../src/microtime.cc:59:51: error: no matching function for call to âNODE_SET_METHOD(v8::Handle<v8::Object>&, const char [10], v8::Handle<v8::Value> (&)(const int&))â
         NODE_SET_METHOD(target, "nowStruct", NowStruct);
                                                       ^
    ../src/microtime.cc:59:51: note: candidate is:
    In file included from ../src/microtime.cc:2:0:
    /root/.node-gyp/0.12.6/src/node.h:228:13: note: template<class TypeName> void node::NODE_SET_METHOD(const TypeName&, const char*, v8::FunctionCallback)
     inline void NODE_SET_METHOD(const TypeName& recv,
                 ^
    /root/.node-gyp/0.12.6/src/node.h:228:13: note:   template argument deduction/substitution failed:
    ../src/microtime.cc:59:51: note:   cannot convert âNowStructâ (type âv8::Handle<v8::Value>(const int&)â) to type âv8::FunctionCallback {aka void (*)(const v8::FunctionCallbackInfo<v8::Value>&)}â
         NODE_SET_METHOD(target, "nowStruct", NowStruct);
                                                       ^
    microtime.target.mk:85: recipe for target 'Release/obj.target/microtime/src/microtime.o' failed
    make: *** [Release/obj.target/microtime/src/microtime.o] Error 1
    make: Leaving directory '/usr/local/src/pasteboard/node_modules/microtime/build'
    gyp ERR! build error
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/usr/lib64/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
    gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
    gyp ERR! System Linux 4.1.12-gentoo
    gyp ERR! command "node" "/usr/lib64/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /usr/local/src/pasteboard/node_modules/microtime
    gyp ERR! node -v v0.12.6
    gyp ERR! node-gyp -v v2.0.1
    gyp ERR! not ok
    npm ERR! Linux 4.1.12-gentoo
    npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "microtime"
    npm ERR! node v0.12.6
    npm ERR! npm  v2.11.2
    npm ERR! code ELIFECYCLE

    npm ERR! microtime@0.3.3 install: `node-gyp rebuild`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the microtime@0.3.3 install script 'node-gyp rebuild'.
    npm ERR! This is most likely a problem with the microtime package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node-gyp rebuild
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls microtime
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     /usr/local/src/pasteboard/npm-debug.log
    themis pasteboard #
    themis pasteboard # uname -a
    Linux themis 4.1.12-gentoo #1 SMP Wed Jan 6 18:28:34 PST 2016 x86_64 Intel(R) Core(TM) i5 CPU M 460 @ 2.53GHz GenuineIntel GNU/Linux
    themis pasteboard #  npm version
    { pasteboard: '0.0.1',
      npm: '2.11.2',
      http_parser: '2.3',
      modules: '14',
      node: '0.12.6',
      openssl: '1.0.2e',
      uv: '1.4.2',
      v8: '3.28.71.19',
      zlib: '1.2.8' }
    themis pasteboard #

**Comment by jlpoolen** [comment]
themis pasteboard # eix net-libs/nodejs
    [I] net-libs/nodejs
         Available versions:  0.12.6^t ~0.12.7^t ~4.1.1 ~4.2.2 ~5.0.0 ~5.3.0 ~5.4.1 {debug icu +npm (+)snapshot +ssl PYTHON_TARGETS="python2_7"}
         Installed versions:  0.12.6^t(09:31:20 PM 01/28/2016)(npm snapshot ssl -debug -icu PYTHON_TARGETS="python2_7")
         Homepage:            http://nodejs.org/
         Description:         Evented IO for V8 Javascript

    themis pasteboard #

**Comment by jlpoolen** [comment]
oops... Gentoo doesn't like Node: I see my version is 0.12.6 which is ancient.  Closing this as I'll install 5.4.1.

**Comment by jlpoolen** [comment]
I updated Nodejs on my Gentoo system to 5.4.1 and still had the same problem, so I'm re-opening this ticket with the results from Nodejs 5.4.1:
    themis pasteboard # npm install microtime

    > microtime@0.3.3 install /usr/local/src/pasteboard/node_modules/microtime
    > node-gyp rebuild

    make: Entering directory '/usr/local/src/pasteboard/node_modules/microtime/build'
      CXX(target) Release/obj.target/microtime/src/microtime.o
    ../src/microtime.cc:10:32: error: âArgumentsâ does not name a type
     static Handle<Value> Now(const Arguments &args) {
                                    ^
    In file included from ../src/microtime.cc:1:0:
    /root/.node-gyp/5.4.1/include/node/v8.h: In function âv8::Handle<v8::Value> Now(const int&)â:
    /root/.node-gyp/5.4.1/include/node/v8.h:889:13: error: âv8::HandleScope::HandleScope()â is protected
       V8_INLINE HandleScope() {}
                 ^
    ../src/microtime.cc:11:17: error: within this context
         HandleScope scope;
                     ^
    ../src/microtime.cc:17:67: warning: âv8::Local<v8::Value> node::ErrnoException(int, const char*, const char*, const char*)â is deprecated (declared at /root/.node-gyp/5.4.1/include/node/node.h:99): Use ErrnoException(isolate, ...) [-Wdeprecated-declarations]
             return ThrowException(ErrnoException(errno, "gettimeofday"));
                                                                       ^
    ../src/microtime.cc:17:68: error: âThrowExceptionâ was not declared in this scope
             return ThrowException(ErrnoException(errno, "gettimeofday"));
                                                                        ^
    ../src/microtime.cc:20:18: error: âclass v8::HandleScopeâ has no member named âCloseâ
         return scope.Close(Number::New((t.tv_sec * 1000000.0) + t.tv_usec));
                      ^
    ../src/microtime.cc:20:70: error: no matching function for call to âv8::Number::New(double)â
         return scope.Close(Number::New((t.tv_sec * 1000000.0) + t.tv_usec));
                                                                          ^
    ../src/microtime.cc:20:70: note: candidate is:
    In file included from ../src/microtime.cc:1:0:
    /root/.node-gyp/5.4.1/include/node/v8.h:2483:24: note: static v8::Local<v8::Number> v8::Number::New(v8::Isolate*, double)
       static Local<Number> New(Isolate* isolate, double value);
                            ^
    /root/.node-gyp/5.4.1/include/node/v8.h:2483:24: note:   candidate expects 2 arguments, 1 provided
    ../src/microtime.cc: At global scope:
    ../src/microtime.cc:23:38: error: âArgumentsâ does not name a type
     static Handle<Value> NowDouble(const Arguments &args) {
                                          ^
    In file included from ../src/microtime.cc:1:0:
    /root/.node-gyp/5.4.1/include/node/v8.h: In function âv8::Handle<v8::Value> NowDouble(const int&)â:
    /root/.node-gyp/5.4.1/include/node/v8.h:889:13: error: âv8::HandleScope::HandleScope()â is protected
       V8_INLINE HandleScope() {}
                 ^
    ../src/microtime.cc:24:17: error: within this context
         HandleScope scope;
                     ^
    ../src/microtime.cc:30:67: warning: âv8::Local<v8::Value> node::ErrnoException(int, const char*, const char*, const char*)â is deprecated (declared at /root/.node-gyp/5.4.1/include/node/node.h:99): Use ErrnoException(isolate, ...) [-Wdeprecated-declarations]
             return ThrowException(ErrnoException(errno, "gettimeofday"));
                                                                       ^
    ../src/microtime.cc:30:68: error: âThrowExceptionâ was not declared in this scope
             return ThrowException(ErrnoException(errno, "gettimeofday"));
                                                                        ^
    ../src/microtime.cc:33:18: error: âclass v8::HandleScopeâ has no member named âCloseâ
         return scope.Close(Number::New(t.tv_sec + (t.tv_usec * 0.000001)));
                      ^
    ../src/microtime.cc:33:69: error: no matching function for call to âv8::Number::New(double)â
         return scope.Close(Number::New(t.tv_sec + (t.tv_usec * 0.000001)));
                                                                         ^
    ../src/microtime.cc:33:69: note: candidate is:
    In file included from ../src/microtime.cc:1:0:
    /root/.node-gyp/5.4.1/include/node/v8.h:2483:24: note: static v8::Local<v8::Number> v8::Number::New(v8::Isolate*, double)
       static Local<Number> New(Isolate* isolate, double value);
                            ^
    /root/.node-gyp/5.4.1/include/node/v8.h:2483:24: note:   candidate expects 2 arguments, 1 provided
    ../src/microtime.cc: At global scope:
    ../src/microtime.cc:36:38: error: âArgumentsâ does not name a type
     static Handle<Value> NowStruct(const Arguments &args) {
                                          ^
    In file included from ../src/microtime.cc:1:0:
    /root/.node-gyp/5.4.1/include/node/v8.h: In function âv8::Handle<v8::Value> NowStruct(const int&)â:
    /root/.node-gyp/5.4.1/include/node/v8.h:889:13: error: âv8::HandleScope::HandleScope()â is protected
       V8_INLINE HandleScope() {}
                 ^
    ../src/microtime.cc:37:17: error: within this context
         HandleScope scope;
                     ^
    ../src/microtime.cc:43:67: warning: âv8::Local<v8::Value> node::ErrnoException(int, const char*, const char*, const char*)â is deprecated (declared at /root/.node-gyp/5.4.1/include/node/node.h:99): Use ErrnoException(isolate, ...) [-Wdeprecated-declarations]
             return ThrowException(ErrnoException(errno, "gettimeofday"));
                                                                       ^
    ../src/microtime.cc:43:68: error: âThrowExceptionâ was not declared in this scope
             return ThrowException(ErrnoException(errno, "gettimeofday"));
                                                                        ^
    ../src/microtime.cc:46:38: error: invalid conversion from âintâ to âv8::Isolate â [-fpermissive]
         Local<Array> array = Array::New(2);
                                          ^
    In file included from ../src/microtime.cc:1:0:
    /root/.node-gyp/5.4.1/include/node/v8.h:2962:23: note: initializing argument 1 of âstatic v8::Local<v8::Array> v8::Array::New(v8::Isolate*, int)â
       static Local<Array> New(Isolate* isolate, int length = 0);
                           ^
    ../src/microtime.cc:47:30: error: no matching function for call to âv8::Integer::New(int)â
         array->Set(Integer::New(0), Uint32::New(t.tv_sec));
                                  ^
    ../src/microtime.cc:47:30: note: candidate is:
    In file included from ../src/microtime.cc:1:0:
    /root/.node-gyp/5.4.1/include/node/v8.h:2496:25: note: static v8::Local<v8::Integer> v8::Integer::New(v8::Isolate*, int32_t)
       static Local<Integer> New(Isolate* isolate, int32_t value);
                             ^
    /root/.node-gyp/5.4.1/include/node/v8.h:2496:25: note:   candidate expects 2 arguments, 1 provided
    ../src/microtime.cc:47:53: error: no matching function for call to âv8::Uint32::New(__time_t&)â
         array->Set(Integer::New(0), Uint32::New(t.tv_sec));
                                                         ^
    ../src/microtime.cc:47:53: note: candidate is:
    In file included from ../src/microtime.cc:1:0:
    /root/.node-gyp/5.4.1/include/node/v8.h:2496:25: note: static v8::Local<v8::Integer> v8::Integer::New(v8::Isolate*, int32_t)
       static Local<Integer> New(Isolate* isolate, int32_t value);
                             ^
    /root/.node-gyp/5.4.1/include/node/v8.h:2496:25: note:   candidate expects 2 arguments, 1 provided
    ../src/microtime.cc:48:30: error: no matching function for call to âv8::Integer::New(int)â
         array->Set(Integer::New(1), Uint32::New(t.tv_usec));
                                  ^
    ../src/microtime.cc:48:30: note: candidate is:
    In file included from ../src/microtime.cc:1:0:
    /root/.node-gyp/5.4.1/include/node/v8.h:2496:25: note: static v8::Local<v8::Integer> v8::Integer::New(v8::Isolate*, int32_t)
       static Local<Integer> New(Isolate* isolate, int32_t value);
                             ^
    /root/.node-gyp/5.4.1/include/node/v8.h:2496:25: note:   candidate expects 2 arguments, 1 provided
    ../src/microtime.cc:48:54: error: no matching function for call to âv8::Uint32::New(__suseconds_t&)â
         array->Set(Integer::New(1), Uint32::New(t.tv_usec));
                                                          ^
    ../src/microtime.cc:48:54: note: candidate is:
    In file included from ../src/microtime.cc:1:0:
    /root/.node-gyp/5.4.1/include/node/v8.h:2496:25: note: static v8::Local<v8::Integer> v8::Integer::New(v8::Isolate*, int32_t)
       static Local<Integer> New(Isolate* isolate, int32_t value);
                             ^
    /root/.node-gyp/5.4.1/include/node/v8.h:2496:25: note:   candidate expects 2 arguments, 1 provided
    ../src/microtime.cc:50:18: error: âclass v8::HandleScopeâ has no member named âCloseâ
         return scope.Close(array);
                      ^
    In file included from ../src/microtime.cc:1:0:
    /root/.node-gyp/5.4.1/include/node/v8.h: In function âvoid init(v8::Handle<v8::Object>)â:
    /root/.node-gyp/5.4.1/include/node/v8.h:889:13: error: âv8::HandleScope::HandleScope()â is protected
       V8_INLINE HandleScope() {}
                 ^
    ../src/microtime.cc:55:17: error: within this context
         HandleScope scope;
                     ^
    ../src/microtime.cc:57:39: error: no matching function for call to âNODE_SET_METHOD(v8::Handle<v8::Object>&, const char [4], v8::Handle<v8::Value> (&)(const int&))â
         NODE_SET_METHOD(target, "now", Now);
                                           ^
    ../src/microtime.cc:57:39: note: candidate is:
    In file included from ../src/microtime.cc:2:0:
    /root/.node-gyp/5.4.1/include/node/node.h:236:13: note: template<class TypeName> void node::NODE_SET_METHOD(const TypeName&, const char*, v8::FunctionCallback)
     inline void NODE_SET_METHOD(const TypeName& recv,
                 ^
    /root/.node-gyp/5.4.1/include/node/node.h:236:13: note:   template argument deduction/substitution failed:
    ../src/microtime.cc:57:39: note:   cannot convert âNowâ (type âv8::Handle<v8::Value>(const int&) {aka v8::Local<v8::Value>(const int&)}â) to type âv8::FunctionCallback {aka void (*)(const v8::FunctionCallbackInfo<v8::Value>&)}â
         NODE_SET_METHOD(target, "now", Now);
                                           ^
    ../src/microtime.cc:58:51: error: no matching function for call to âNODE_SET_METHOD(v8::Handle<v8::Object>&, const char [10], v8::Handle<v8::Value> (&)(const int&))â
         NODE_SET_METHOD(target, "nowDouble", NowDouble);
                                                       ^
    ../src/microtime.cc:58:51: note: candidate is:
    In file included from ../src/microtime.cc:2:0:
    /root/.node-gyp/5.4.1/include/node/node.h:236:13: note: template<class TypeName> void node::NODE_SET_METHOD(const TypeName&, const char*, v8::FunctionCallback)
     inline void NODE_SET_METHOD(const TypeName& recv,
                 ^
    /root/.node-gyp/5.4.1/include/node/node.h:236:13: note:   template argument deduction/substitution failed:
    ../src/microtime.cc:58:51: note:   cannot convert âNowDoubleâ (type âv8::Handle<v8::Value>(const int&) {aka v8::Local<v8::Value>(const int&)}â) to type âv8::FunctionCallback {aka void (*)(const v8::FunctionCallbackInfo<v8::Value>&)}â
         NODE_SET_METHOD(target, "nowDouble", NowDouble);
                                                       ^
    ../src/microtime.cc:59:51: error: no matching function for call to âNODE_SET_METHOD(v8::Handle<v8::Object>&, const char [10], v8::Handle<v8::Value> (&)(const int&))â
         NODE_SET_METHOD(target, "nowStruct", NowStruct);
                                                       ^
    ../src/microtime.cc:59:51: note: candidate is:
    In file included from ../src/microtime.cc:2:0:
    /root/.node-gyp/5.4.1/include/node/node.h:236:13: note: template<class TypeName> void node::NODE_SET_METHOD(const TypeName&, const char*, v8::FunctionCallback)
     inline void NODE_SET_METHOD(const TypeName& recv,
                 ^
    /root/.node-gyp/5.4.1/include/node/node.h:236:13: note:   template argument deduction/substitution failed:
    ../src/microtime.cc:59:51: note:   cannot convert âNowStructâ (type âv8::Handle<v8::Value>(const int&) {aka v8::Local<v8::Value>(const int&)}â) to type âv8::FunctionCallback {aka void (*)(const v8::FunctionCallbackInfo<v8::Value>&)}â
         NODE_SET_METHOD(target, "nowStruct", NowStruct);
                                                       ^
    microtime.target.mk:88: recipe for target 'Release/obj.target/microtime/src/microtime.o' failed
    make: *** [Release/obj.target/microtime/src/microtime.o] Error 1
    make: Leaving directory '/usr/local/src/pasteboard/node_modules/microtime/build'
    gyp ERR! build error
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/usr/lib64/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
    gyp ERR! stack     at emitTwo (events.js:87:13)
    gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
    gyp ERR! System Linux 4.1.12-gentoo
    gyp ERR! command "/usr/bin/node" "/usr/lib64/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /usr/local/src/pasteboard/node_modules/microtime
    gyp ERR! node -v v5.4.1
    gyp ERR! node-gyp -v v3.0.3
    gyp ERR! not ok
    npm ERR! Linux 4.1.12-gentoo
    npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "microtime"
    npm ERR! node v5.4.1
    npm ERR! npm  v3.3.12
    npm ERR! code ELIFECYCLE

    npm ERR! microtime@0.3.3 install: `node-gyp rebuild`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the microtime@0.3.3 install script 'node-gyp rebuild'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
    npm ERR! If you do, this is most likely a problem with the microtime package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node-gyp rebuild
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls microtime
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     /usr/local/src/pasteboard/npm-debug.log
    themis pasteboard #

**Comment by wadey** [comment]
@jlpoolen please use a newer version of microtime. `0.3.3` is outdated (released in 2012) and doesn't work with the latest versions of Node.js.

**Comment by jlpoolen** [comment]
Thank you, Wade. I'm not familiar with npm, but following the instructions at:  https://docs.npmjs.com/cli/install doesn't seem to be working for me:

    themis pasteboard # npm install microtime@2.0.0

    > microtime@2.0.0 install /usr/local/src/pasteboard/node_modules/microtime
    > node-gyp rebuild

    make: Entering directory '/usr/local/src/pasteboard/node_modules/microtime/build'
      CXX(target) Release/obj.target/microtime/src/microtime.o
      SOLINK_MODULE(target) Release/obj.target/microtime.node
      COPY Release/microtime.node
    make: Leaving directory '/usr/local/src/pasteboard/node_modules/microtime/build'
    pasteboard@0.0.1 /usr/local/src/pasteboard
    `-- microtime@2.0.0  invalid
      +-- bindings@1.2.1
      `-- nan@2.0.9

    themis pasteboard # npm install microtime@latest

    > microtime@2.0.0 install /usr/local/src/pasteboard/node_modules/microtime
    > node-gyp rebuild

    make: Entering directory '/usr/local/src/pasteboard/node_modules/microtime/build'
      CXX(target) Release/obj.target/microtime/src/microtime.o
      SOLINK_MODULE(target) Release/obj.target/microtime.node
      COPY Release/microtime.node
    make: Leaving directory '/usr/local/src/pasteboard/node_modules/microtime/build'
    pasteboard@0.0.1 /usr/local/src/pasteboard
    `-- microtime@2.0.0  invalid

    themis pasteboard # npm install microtime@1.5.0

    > microtime@1.5.0 install /usr/local/src/pasteboard/node_modules/microtime
    > node-gyp rebuild

    make: Entering directory '/usr/local/src/pasteboard/node_modules/microtime/build'
      CXX(target) Release/obj.target/microtime/src/microtime.o
      SOLINK_MODULE(target) Release/obj.target/microtime.node
      COPY Release/microtime.node
    make: Leaving directory '/usr/local/src/pasteboard/node_modules/microtime/build'
    pasteboard@0.0.1 /usr/local/src/pasteboard
    `-- microtime@1.5.0  invalid

    themis pasteboard # npm install https://github.com/wadey/node-microtime.git

    > microtime@2.0.0 install /usr/local/src/pasteboard/node_modules/microtime
    > node-gyp rebuild

    make: Entering directory '/usr/local/src/pasteboard/node_modules/microtime/build'
      CXX(target) Release/obj.target/microtime/src/microtime.o
      SOLINK_MODULE(target) Release/obj.target/microtime.node
      COPY Release/microtime.node
    make: Leaving directory '/usr/local/src/pasteboard/node_modules/microtime/build'
    pasteboard@0.0.1 /usr/local/src/pasteboard
    `-- microtime@2.0.0  invalid (git+https://github.com/wadey/node-microtime.git#1852b5544a5de322b614413e00e0d05c1561bb5d)

    themis pasteboard #

**Comment by wadey** [comment]
You probably need to update the version inside of the `package.json` file.

**Comment by jlpoolen** [comment]
Thank you, your suggestion worked.  I modified the package.json and now it runs.
