### ISSUE TITLE
Publishing new version to npm

### ISSUE THREAD

**Issue by ruimarinho** [wadey/node-microtime#42]
Now that node v6 is out, nan 2.2.x is required to compile the addon. Can you publish the changes on master to npm? Thanks!

**Comment by wadey** [comment]
Thanks for the reminder. I'll publish it when I get back to my computer, within the next 24 hours.

**Comment by wadey** [comment]
published `microtime 2.1.0`.

**Comment by ruimarinho** [comment]
Awesome, thanks a lot!
