### ISSUE TITLE
Error installing with npm

### ISSUE THREAD

**Issue by Lerosen** [wadey/node-microtime#46]
Hello,
i get an error on 'node-gyp rebuild' in the intallation script when trying to install via npm install microtime. I already updated node and npm, but it didnt help. I also ensured that g++ ist installed.

node v6.6.0
npm  v3.10.8

[npm-debug.log.txt](https://github.com/wadey/node-microtime/files/491881/npm-debug.log.txt)

**Comment by wadey** [comment]
Was there other output besides this npm-debug log? This debug log doesn't not show the error message from node-gyp, just that it failed. I need the output from node-gyp to help debug this. Check if there is other output from running `npm install` other than this log file.

**Comment by Lerosen** [comment]
At the moment I get a "segmentation fault" a whatever i try with nod/npm. Its strange because I did not change anything overnight. I will report back when i fixed this to provide you more information. D:

**Comment by Lerosen** [comment]
Ok, so i finally got npm working gain.
I put the log on Pastebin. http://pastebin.com/GCRYbyCx

**Comment by wadey** [comment]
Please update to a newer version of microtime, it looks like you are trying to install 0.4.0, which does not work with the latest versions of Node.

**Comment by Lerosen** [comment]
Ok im sorry :3 did it with `npm install microtime@latest` and now it worked. I thought the default install would use the latest version as well ... Thank you for your help tho, I was very frustrated after 3 hours of trying to get it working and in the end it was that simple ^^
