### ISSUE TITLE
Microtime install stucks in endless loop with node 8

### ISSUE THREAD

**Issue by megastef** [wadey/node-microtime#55]
See issue: https://github.com/sematext/logagent-js/issues/121

**Comment by wadey** [comment]
It looks like you are running `npm` as the root user. This is not supported by `prebuild-install`, and you need to add the `--unsafe-perm` flag. Please open the issue with https://github.com/prebuild/prebuild-install .

**Comment by wadey** [comment]
Actually see this long ticket that is discussing the same issue: https://github.com/nodejs/node-gyp/issues/454#issuecomment-315691803
